export const PROJECT_CONFIG = {
  STEPS: {
    GITHUB_APP: "github-app",
    PROJECT_DETAILS: "project-details",
    CREATING: "creating",
  } as const,
  API_ENDPOINTS: {
    GITHUB_INSTALLATION_STATUS: "/github/installation/status",
    CREATE_PROJECT: "/projects",
  },
  TEXT: {
    WIZARD_TITLE: "Create New Project",
    STEP_GITHUB_APP: {
      TITLE: "Connect GitHub",
      DESCRIPTION: "Install the Secrin GitHub App to enable repository creation",
      CHECKING: "Checking GitHub App installation...",
      INSTALLED: "GitHub App is installed! You're ready to proceed.",
      NOT_INSTALLED: "To create projects, you need to install the Secrin GitHub App.",
      INSTALL_BUTTON: "Install GitHub App",
      CHECK_BUTTON: "Check Installation",
      CONTINUE_BUTTON: "Continue",
    },
    STEP_PROJECT_DETAILS: {
      TITLE: "Project Details",
      DESCRIPTION: "Enter your project information",
      NAME_LABEL: "Project Name",
      NAME_PLACEHOLDER: "My Awesome Project",
      DESCRIPTION_LABEL: "Description (optional)",
      DESCRIPTION_PLACEHOLDER: "A brief description of your project",
      REPO_NAME_LABEL: "Repository Name",
      REPO_NAME_PLACEHOLDER: "my-awesome-project",
      REPO_NAME_HINT: "This will be created in your GitHub account",
      CREATE_BUTTON: "Create Project",
      BACK_BUTTON: "Back",
    },
    STEP_CREATING: {
      TITLE: "Creating Project",
      DESCRIPTION: "Setting up your project and repository...",
      CREATING_REPO: "Creating repository in your GitHub account...",
      SETTING_UP: "Setting up project configuration...",
      SUCCESS: "Project created successfully!",
      ERROR: "Failed to create project. Please try again.",
      VIEW_PROJECT: "View Project",
      VIEW_REPO: "View Repository",
      TRY_AGAIN: "Try Again",
    },
    ERROR_GENERIC: "Something went wrong. Please try again.",
  },
} as const;
