version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: devsecrin
      POSTGRES_USER: devsecrin
      POSTGRES_PASSWORD: devsecrin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/dbup/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsecrin"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Ollama Service (for local AI model)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

  # DevSecrin Application
  devsecrin:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://devsecrin:devsecrin@postgres:5432/devsecrin
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=deepseek-r1:1.5b
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_store
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./chroma_store:/app/chroma_store
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
