#!/usr/bin/env python3
"""
Quick setup script for Secrin configuration.
Helps with initial configuration and validation.
"""

import sys
from pathlib import Path
from typing import Optional

# Add project root to path
project_root = Path(__file__).resolve().parent
sys.path.insert(0, str(project_root))


def check_env_file() -> bool:
    """Check if .env file exists."""
    env_path = project_root / ".env"
    return env_path.exists()


def create_env_from_example() -> bool:
    """Create .env from .env.example."""
    example_path = project_root / ".env.example"
    env_path = project_root / ".env"
    
    if not example_path.exists():
        print("❌ .env.example not found!")
        return False
    
    if env_path.exists():
        response = input(".env already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Keeping existing .env file")
            return True
    
    # Copy example to .env
    with open(example_path, 'r') as f:
        content = f.read()
    
    with open(env_path, 'w') as f:
        f.write(content)
    
    print("✅ Created .env from .env.example")
    return True


def run_validation() -> bool:
    """Run configuration validation."""
    from packages.config.utils import validate_required_settings
    
    is_valid, missing = validate_required_settings()
    
    if is_valid:
        print("✅ Configuration is valid!")
        return True
    else:
        print("❌ Configuration is incomplete!")
        print("\nMissing required settings:")
        for setting in missing:
            print(f"  • {setting}")
        return False


def prompt_for_settings() -> dict:
    """Prompt user for essential settings."""
    print("\n" + "="*70)
    print("Essential Configuration")
    print("="*70)
    
    settings = {}
    
    # Neo4j settings
    print("\n📊 Neo4j Database Configuration")
    settings['NEO4J_URI'] = input("Neo4j URI [bolt://localhost:7687]: ").strip() or "bolt://localhost:7687"
    settings['NEO4J_USER'] = input("Neo4j User [neo4j]: ").strip() or "neo4j"
    settings['NEO4J_PASS'] = input("Neo4j Password: ").strip()
    settings['NEO4J_DB'] = input("Neo4j Database [neo4j]: ").strip() or "neo4j"
    
    # Embedding provider
    print("\n🤖 Embedding Provider Configuration")
    print("1. Ollama (recommended for local development)")
    print("2. OpenAI (requires API key)")
    print("3. Sentence Transformer (local model)")
    
    choice = input("Choose provider [1]: ").strip() or "1"
    
    if choice == "1":
        settings['EMBEDDING_PROVIDER'] = "ollama"
        settings['OLLAMA_BASE_URL'] = input("Ollama URL [http://localhost:11434]: ").strip() or "http://localhost:11434"
        settings['OLLAMA_EMBEDDING_MODEL'] = input("Model [mxbai-embed-large]: ").strip() or "mxbai-embed-large"
        settings['EMBEDDING_DIMENSION'] = "1024"
    elif choice == "2":
        settings['EMBEDDING_PROVIDER'] = "openai"
        settings['OPENAI_API_KEY'] = input("OpenAI API Key: ").strip()
        settings['OPENAI_EMBEDDING_MODEL'] = input("Model [text-embedding-3-small]: ").strip() or "text-embedding-3-small"
        settings['EMBEDDING_DIMENSION'] = "1536"
    else:
        settings['EMBEDDING_PROVIDER'] = "sentence_transformer"
        settings['SENTENCE_TRANSFORMER_MODEL'] = input("Model [sentence-transformers/all-MiniLM-L6-v2]: ").strip() or "sentence-transformers/all-MiniLM-L6-v2"
        settings['EMBEDDING_DIMENSION'] = "384"
    
    # Environment
    print("\n🌍 Environment Configuration")
    settings['ENVIRONMENT'] = input("Environment [development]: ").strip() or "development"
    settings['LOG_LEVEL'] = input("Log Level [INFO]: ").strip() or "INFO"
    
    return settings


def update_env_file(settings: dict) -> None:
    """Update .env file with new settings."""
    env_path = project_root / ".env"
    
    # Read existing content
    existing = {}
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    existing[key.strip()] = value.strip()
    
    # Update with new settings
    existing.update(settings)
    
    # Write back
    with open(env_path, 'w') as f:
        # Write header
        f.write("# Secrin Configuration\n")
        f.write("# Generated by setup_config.py\n\n")
        
        # Write settings by category
        categories = {
            'Environment': ['ENVIRONMENT', 'DEBUG', 'LOG_LEVEL'],
            'Neo4j': ['NEO4J_URI', 'NEO4J_USER', 'NEO4J_PASS', 'NEO4J_DB'],
            'Embedding': ['EMBEDDING_PROVIDER', 'EMBEDDING_DIMENSION', 
                         'OPENAI_API_KEY', 'OPENAI_EMBEDDING_MODEL',
                         'OLLAMA_BASE_URL', 'OLLAMA_EMBEDDING_MODEL',
                         'SENTENCE_TRANSFORMER_MODEL'],
        }
        
        for category, keys in categories.items():
            f.write(f"# {category}\n")
            for key in keys:
                if key in existing:
                    f.write(f"{key}={existing[key]}\n")
            f.write("\n")
        
        # Write remaining settings
        f.write("# Other Settings\n")
        for key, value in existing.items():
            if not any(key in cat_keys for cat_keys in categories.values()):
                f.write(f"{key}={value}\n")
    
    print("\n✅ Configuration saved to .env")


def test_connection() -> bool:
    """Test Neo4j connection."""
    try:
        from packages.database.graph.graph import Neo4jClient
        
        print("\n🔌 Testing Neo4j connection...")
        client = Neo4jClient()
        result = client.run_query("RETURN 1 as test")
        
        if result and result[0]["test"] == 1:
            print("✅ Neo4j connection successful!")
            return True
        else:
            print("❌ Neo4j connection failed: Unexpected response")
            return False
    except Exception as e:
        print(f"❌ Neo4j connection failed: {e}")
        return False


def print_summary() -> None:
    """Print configuration summary."""
    from packages.config.utils import print_config_summary
    
    print("\n")
    print_config_summary()


def main():
    """Main setup flow."""
    print("=" * 70)
    print("Secrin Configuration Setup")
    print("=" * 70)
    
    # Step 1: Check for .env file
    if not check_env_file():
        print("\n.env file not found.")
        response = input("Create from .env.example? (Y/n): ")
        if response.lower() != 'n':
            if not create_env_from_example():
                print("\n❌ Setup failed!")
                sys.exit(1)
    
    # Step 2: Validate existing configuration
    print("\n📋 Validating configuration...")
    is_valid = run_validation()
    
    if not is_valid:
        print("\n⚙️  Let's configure the required settings.")
        response = input("Start interactive setup? (Y/n): ")
        
        if response.lower() != 'n':
            settings = prompt_for_settings()
            update_env_file(settings)
            
            # Validate again
            print("\n📋 Validating updated configuration...")
            is_valid = run_validation()
    
    if not is_valid:
        print("\n⚠️  Please manually edit .env file with required settings")
        print("See .env.example for reference")
        sys.exit(1)
    
    # Step 3: Test connection
    response = input("\n🔌 Test Neo4j connection? (Y/n): ")
    if response.lower() != 'n':
        test_connection()
    
    # Step 4: Show summary
    response = input("\n📊 Show configuration summary? (Y/n): ")
    if response.lower() != 'n':
        print_summary()
    
    print("\n" + "=" * 70)
    print("✅ Setup Complete!")
    print("=" * 70)
    print("\nNext steps:")
    print("  1. Review configuration: python -m packages.config.cli summary")
    print("  2. View feature flags: python -m packages.config.cli flags")
    print("  3. Check documentation: docs/CONFIGURATION.md")
    print("  4. Start using Secrin!")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
