version: "3.9"

services:
  # ollama:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ollama
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags || exit 1"]
  #     interval: 15s
  #     timeout: 10s
  #     retries: 10
  #     start_period: 20s


  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  devsecrin-api:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    image: devsecrin-api:latest
    container_name: devsecrin-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
      - REDIS_SERVER_URL=redis://redis:6379
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_store
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ../gemini_store:/app/gemini_store
      - ../chroma_store:/app/chroma_store
      - ../logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      # ollama:
      #   condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  # ollama_data:
  redis_data:
