from fastapi import status

# Success
OK = status.HTTP_200_OK
CREATED = status.HTTP_201_CREATED
ACCEPTED = status.HTTP_202_ACCEPTED
NO_CONTENT = status.HTTP_204_NO_CONTENT

# Client Errors
BAD_REQUEST = status.HTTP_400_BAD_REQUEST
UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
FORBIDDEN = status.HTTP_403_FORBIDDEN
NOT_FOUND = status.HTTP_404_NOT_FOUND
CONFLICT = status.HTTP_409_CONFLICT
UNPROCESSABLE_ENTITY = status.HTTP_422_UNPROCESSABLE_ENTITY

# Server Errors
INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
NOT_IMPLEMENTED = status.HTTP_501_NOT_IMPLEMENTED
SERVICE_UNAVAILABLE = status.HTTP_503_SERVICE_UNAVAILABLE
